### ISSUE TITLE
issue of 'fix browser history router'

### ISSUE THREAD

**Issue by sandcforge** [antonfisher/react-express-webpack2#1]
Hi antonfisher,
Thanks for your repo.
I am a frontend beginner, and start to learn webpack.
may I know the reason you place 
`    if (req.url !== '/' && !req.url.includes('.')) {
      request('http://localhost:${process.env.APP_PORT}/', (error, response, body) => res.end(body));
    } else {
      res.sendFile(resolve(compiler.outputPath, 'index.html'));
    }
`
in the `  app.get('*',` ...
I try to remove this and use only `res.sendFile(resolve(compiler.outputPath, 'index.html'));`, it fails.
I know this is a workaround, but have you figured out a decent way to fix it?

Thanks,
Chen

**Comment by antonfisher** [comment]
Hi Chen,

There was an issue in case you trying to open `http://localhost:3000/users` directly in the browser by typing full url in the address field. And files like `/main.js` were responded with `index.html` content instead of real files content. I guess, this behavior was the result of my webpack config changes and I created the fix instead of getting deeper into the issue...
I believe, the initial issue appeared when I renamed main js file from `app.js` to `main.js`, and forgot to run `npm run build` what generates new index.html.

All seems working for me now without this workaround.
This is a good catch! I don't see the reason to keep it now, I'll update the code.

Thank you!

**Comment by sandcforge** [comment]
Hey antonfisher,
Thanks for your quick response.
However, when I tried my side it is still has the same behavior, when type 'http://localhost:3000/users' in the address bar directly.
`
> NODE_ENV=development node ./src/server

2017-07-11T04:50:21.259Z - info: Application logs file: /Users/lc/Documents/proj/nodejs/react-express-webpack2/.application.log
2017-07-11T04:50:22.170Z - info: HTTP server is now running on http://localhost:3000
webpack built fef53b4136059d430fd8 in 9402ms
Hash: fef53b4136059d430fd8
Time: 9402ms
chunk    {0} main.js (main) 115 kB {1} [initial] [rendered]
chunk    {1} vendor.js (vendor) 2.54 MB [entry] [rendered]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 670 bytes [entry] [rendered]
webpack: Compiled successfully.
2017-07-11T04:50:39.195Z - info: GET /users
2017-07-11T04:50:39.202Z - info: GET /users - 200 - 0.007s
Error: ENOENT: no such file or directory, stat '/Users/lc/Documents/proj/nodejs/react-express-webpack2/build/client/index.html'
`
Thanks,
Chen

**Comment by sandcforge** [comment]
Hi antonfisher,
Thanks for your quick response.
Does that mean, in the development evironment, I have to run 'npm run build' to generate index.html first, then I could run 'npm run dev'? Because right now I still has the same issue even with the latest trunk.
Is there any way to remove this extra step?

Thanks,
Chen

**Comment by antonfisher** [comment]
Yeah, I've had this file pre-generated...
I found a plugin which solves the issue: https://github.com/jantimon/html-webpack-harddisk-plugin, it simply saves dev `index.html` file to the disk.
Now `npm run dev` will work without `npm run build`.
Thank you!

**Comment by sandcforge** [comment]
Thanks! I fix my issue.
